### ISSUE TITLE
Russian char

### ISSUE THREAD

**Issue by maxpoland** [m-click/mcpdf#22]
After form fill I see empty pdf, 
when I click on a field, it shows me correct chars.

after flatten I see nothing in filled fields.

please suggest.

**Comment by vog** [comment]
At a first glance, this seems to be an error in the tool that generated your form. But I can't say for sure.

**Comment by maxpoland** [comment]
@vog thanks for your reply.
I tried it with 2 files. 
I used Template PDF from MCPDF itself, which shows me Russian chars correctly.
but after I flatten it hides everything in form fields, even the English chars as well.

**Comment by maxpoland** [comment]
maybe you can send me sample with code please ?

**Comment by vog** [comment]
I don't know what you mean with "code". All code is here in the GitHub repository.

I remember that we had a broken PDF template in the past, where also text disappeared that was entered into the form. Back then, our only solution was to generate the PDF form with a different program (LibreOffice is quite good at that).

Hope that help.

**Comment by maxpoland** [comment]
By code I mean, if you have working fully example with 
php code and pdf file.
If you can send that would be great.

thanks

**Comment by vog** [comment]
I still don't understand. Mcpdf is a Java command-line tool. There's no PHP code involved at all.

**Comment by maxpoland** [comment]
yes it is,
but it can be used in php, I am doing is very successfully,
only problem I have is flatten issue which I shared.

**Comment by vog** [comment]
Okay, to keep this short:

* I don't see any issue with PHP or the command line, as this is what obviously works perfectly fine on your side.
* Regarding the PDF form, I don't have any such forms that I could share freely.

I propose that you create a very small PDF form, maybe just a single text field, with LibreOffice or some other tool. Then, try to fill in values for that. If that still fails, please post it here, so we have a starting point for further investigation.

**Comment by vog** [comment]
@zip1798 I'm glad you were able to solve your issue.
