### ISSUE TITLE
Wrong Readme

### ISSUE THREAD

**Issue by kholat** [m-click/mcpdf#26]
I know this is like 7 years old but to whoever stumbles like me, this is totally not a solution and is hacky af, first of the readme is total bollocks its not a drop in replacement for pdftk at all the syntax is different, secondly it doesnt even work. I have a case where im trying to first generate an FDF, then fill the FDF, then merge the FDF with the actual PDF doc to fill it, this program cannot even WORK with FDF it only works with XFDF, look for a solution elsewhere.

**Comment by vog** [comment]
Improved README.
