### ISSUE TITLE
Note the license more prominently

### ISSUE THREAD

**Issue by karelbilek** [m-click/mcpdf#28]
This project uses Affero GPL, I guess because of its dependence on iText which is AGPL, but it's not really mentioned anywhere except in pom.xml.

This should be described more prominently. Some people do not want to use Affero-licensed code.

**Comment by vog** [comment]
Pull requests are welcome, including pull requests for our main README file.

**Comment by karelbilek** [comment]
okay! It feels weird to "change" license in a PR :) but I will

**Comment by zvezdochiot** [comment]
Hi @karelbilek .

See also [debian-license: AGPL](https://github.com/Text-extend-tools/debian-license/tree/main/usr/share/doc/license/agpl).

**Comment by vog** [comment]
Thanks!
