### ISSUE TITLE
java.lang.RuntimeException: Missing arguments

### ISSUE THREAD

**Issue by kayvax** [m-click/mcpdf#6]
Hi, I have tried to use mcpdf as drop-in replacement for pdftk. It fails me whenever I tried to run it.
I suspected that it did not like oracle-jdk-bin so I tested with icedtea-bin but no avail. I have even tried to build it mysefl and even though build was successful  I have the same issues.

Example:
$ mcpdf -h
java.lang.RuntimeException: Missing arguments.
See README for more information.

$ java -jar mcpdf-0.2.2-SNAPSHOT-jar-with-dependencies.jar 
java.lang.RuntimeException: Missing arguments.
See README for more information.

I am running funtoo linux, if there would be any more information needed I will try to provide it.
best regards

**Comment by vog** [comment]
There is no option "-h" or "usage text" implemented yet, so it points you to the README where you can find all currently supported commands.

Note that although the goal of McPdf is a drop-in replacement for PDFtk, we're not quite there. Essentially, only form-filling is implemented yet (see README), with the `cat` operation upcoming as soon as somebody takes care of #5.

Feel free to propose/implement other commands that you need.

Also, patches for a better "usage"/"-h" message are welcome.

**Comment by kayvax** [comment]
Thanks for prompt response. That explains everything. 
best regards
