### ISSUE TITLE
Can't fill_form with XFDF

### ISSUE THREAD

**Issue by vnenrico** [m-click/mcpdf#7]
Hi guys,

I'm having a problem with mcpdf: when I execute fill_form command, only checkboxes are filled. Other text fields aren't. The FORM.pdf used to work with PDFtk for all fields. 

Do you have any idea?

Thanks.

**Comment by vog** [comment]
This issue is almost impossible to debug without a minimal example.

**Comment by vnenrico** [comment]
Sorry, can you try with below inputs? And the "flatten" keyword does not work either... 

FORM.pdf 
https://drive.google.com/file/d/0ByYhqXwgUnWEeFB1V2tXRmItVms/view?usp=sharing

DATA.xfdf
https://drive.google.com/file/d/0ByYhqXwgUnWEbG8xREhLTWt1N1E/view?usp=sharing

**Comment by vog** [comment]
(Quick note: Your DATA.xfdf is invalid XML. In line 18, there is some special character that looks like `"` but really is some other Unicode character. After fixing that, I was able to reproduce this issue.)

I believe there's something strange with your `FORM.pdf`.

PDFtk silently fixes this issue, while the iTextPDF library (as used by Mcpdf) doesn't. You can see this by opening `FORM.pdf` in Evince. Whenever you enter something into a form field, the value becomes invisible as soon as you leave that form field. When you click on that form field, the entered text appears again.

The same thing happens after filling the form with Mcpdf. You can open the `RESULT.pdf` in Evince, click on that field, and you see your value `abc` appearing. Click on a different place, and the text vanishes.

To summarize, there's nothing Mcpdf can do here. I propose the following future steps to get your issue solved:

* Either `FORM.pdf` is not a 100% valid PDF file, in which case you should try to modify/fix that file, and check with an alternative PDF viewer like Evince or Okular until the text fields no longer vanish.
* Or you are sure that `FORM.pdf` is perfectly valid, but makes use of some PDF feature that neither the iTextPDF library nor Evince support yet. If you believe this is the case, you should [file a bug report to the iTextPDF library](http://itextpdf.com/product/itext).
I verified that the latest iTextPDF version 5.5.5 suffers the same issues.
 * If you have trouble finding their issue tracker (I didn't find any in a quick search), you should tell them about this issue in the [iTextPDF mailing list](http://sourceforge.net/p/itext/mailman/).

**Comment by vnenrico** [comment]
Thanks a log @vog 

Yes, the main reason is because FORM.pdf is not valid, all fields was lock. After unlocking fields, I'm able to fill form now. Great tool!
